### ISSUE TITLE
This is a great library

### ISSUE THREAD

**Issue by MinisculeGirraffe** [resyncgg/dacquiri#22]
This isn't an actual issue. I just wanted to let you know this is a cool library and i've enjoyed using it.

**Comment by d0nutptr** [comment]
Wow! Thank you so much!

Let me know if you run into any limitations :)

I hope to have an update out at some point in December that will increase the expressiveness of dacquiri and allow it to more easily be used to build libraries with authorization constraints baked in.

Have an awesome day! You certainly just made mine :)
