### ISSUE TITLE
Type level contains operation without using unstable `#[marker_trait]`

### ISSUE THREAD

**Issue by weiznich** [resyncgg/dacquiri#25]
Hi Nathanial,

I'm that person that suggested this wired Nathanial with the many `No` and `Yes` types after your talk at eurorust. You've suggested that it might be useful to have a writeup of that idea, as that might be easier to follow. As I had some time on my way back I've produced [this blog post](https://blog.weiznich.de/blog/eurorust-non-overlapping-contains-for-hlists/) about the problem and my proposed solution.

(Sorry about opening an issue about that, it just seems to be the easiest way to get that to your attention)

Best,
Weiznich

**Comment by d0nutptr** [comment]
Hey! Thanks for following up! I really appreciate it :)

Sorry it took a bit to get back to you. My github notifications need some cleaning up honestly :) 

I'll take a look at this in the near future and see if I can remove another unstable feature flag!

Will close this for now
